#!/usr/bin/env python

import sys

from rqt_eyedropper.eyedrop import Eyedrop
from rqt_gui.main import Main

plugin = 'rqt_eyedropper'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
